### ISSUE TITLE
Godot 4 Tracker

### ISSUE THREAD

**Issue by fire** [Geequlim/ECMAScript#131]
Here's my current work on porting to godot 4.

https://github.com/fire/ECMAScript/tree/next

I got stuck. Need some help.

**Comment by Geequlim** [comment]
I have more plans for this project including embedding V8 backend, using NodeJS in the editor, etc. Sadly I haven't been able to find enough time yet to implement them.

I'd like to see how much real world godot users are accepting of JavaScript.

**Comment by Geequlim** [comment]
> I got stuck. Need some help.
You can tell me the problem you're having and I'll be happy to help.

**Comment by fire** [comment]
@Geequlim Can I call you on discord? Want to see if I can send you the code and a description of the current issues so you can assist.

**Comment by Geequlim** [comment]
@fire I don't using dicord that much. And I don't have the confidence to understand or express myself correctly with English. 

Can you describe your problem here? There is a big time difference between us and I will try to help you as much as possible when I am avaliable.

**Comment by fire** [comment]
https://github.com/fire/ECMAScript/tree/next doesn't compile. 

Don't know how to reduce the complexity so I can finish porting it.

**Comment by Geequlim** [comment]
@fire I have pulled your code down and made some changes.
I have pulled your code down and made some changes. 
Since I haven't modified the godot source code for too long, the main problem at the moment is that all of my IDEs are broken.

**Comment by fire** [comment]
Let me know if you have godot 4 questions.

**Comment by Geequlim** [comment]
Downgraded QtCreator to 4.x and it finally worked.
@fire  Did you build the code on the Windows platform? QuickJS doesn't support MSVC yet, so it is recommended that you try to build with mingw.

We create binding code for built-in types through xml documents.
I noticed the errors from generated code is caused as the `argument` is changed to `param` in 4.0, so change it to `param` should fix that.
https://github.com/fire/ECMAScript/blob/next/generate_builtin_api.py#L382

For PackedByteArray we'd better ignore all the methods make errors for now.

**Comment by fire** [comment]
I uses ming llvm. Did you post your changes anywhere?

**Comment by Geequlim** [comment]
> I uses mingw llvm. Did you post your changes anywhere?

@fire https://github.com/Geequlim/ECMAScript/tree/gd4

**Comment by fire** [comment]
What does `FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/ECMAScript/ECMAScript/doc/classes/Quaternion.xml':` mean?

**Comment by Geequlim** [comment]
@fire  The buitin math type binding code is generated from xml doc files in build script. I think I have fixed these compile errors in branch gd4

**Comment by fire** [comment]
Can you repeat the tasks that are open for g4?

**Comment by Geequlim** [comment]
The gd4 branch is for godot 4 I have fixed the compile errors.

**Comment by fire** [comment]
The cicd actions is still failing.

**Comment by fire** [comment]
The javascript rename was merged.

**Comment by fire** [comment]
Can you describe how to do this?  Implements JavaScript and JavaScriptInstance for godot

**Comment by Geequlim** [comment]
That shouldn't be same with 3.x.
We need to fix the code to fit the 4.0 workflow

**Comment by fire** [comment]
Do you have a test project so I can check what works and doesn't work?

**Comment by Geequlim** [comment]
Here are demos for godot 3.x you can reference.

https://github.com/Geequlim/ECMAScriptDemos

**Comment by Geequlim** [comment]
The script workflow for godot 4.0 is implemented in `gd4` branch now.
We can play javascript in godot editor now.

**Comment by fire** [comment]
Would you be interested if I fixed the cicd? Is there anything I should know?

**Comment by fire** [comment]
I was able to get javascript to build, what's a hello world script?

**Comment by Geequlim** [comment]
You can create a script for a node  in the editor as same as GDScript with script create dialog

**Comment by Geequlim** [comment]
> Would you be interested if I fixed the cicd? Is there anything I should know?

Still not found enough time to finish port all the things. These are something missing for the binding side thought. Contributions welcomed

**Comment by Mantissa-23** [comment]
Is there anything I can do to help out here? Not 100% clear on what the state of things are after reading through the thread.

**Comment by CristianPi** [comment]
@Geequlim 
i have errors in the build, probably because of the refactor on the GDScript side (fresh from godot github)

**Comment by fire** [comment]
https://github.com/Geequlim/ECMAScript/tree/gd4 has a recent merge for Godot Engine 4.0 support.

I am going to close this in favour of new bug reports!

Thanks

**Comment by Geequlim** [comment]
Built-in methods which need bind manually in `@GlobScope` and `GDScript` is not fully checked yet.
